Dev
Microverse-Sessions/newsweek-clone pull request #2
Opened 2020-11-05 16:32 UTC by kunmi02

2020-11-05 18:39 UTC, MuriloRoque requested changes
## Status: Changes Requested 🔴 

### Hello @kunmi02 and @bashforger 👋 

### Wow, your page is magnificent, I could barely find anything to suggest, but I still found some details, please check my suggestions:

- [ ] Your page has a horizontal scroll on all page sizes, you should solve this problem as the original doesn't have it. This is bad because the user might have a bad experience if he/she needs to scroll in order to see some of the content:

![Yours1](https://user-images.githubusercontent.com/59691171/98282013-58229800-1f7c-11eb-81b6-fd54272203b4.png)

- [ ] When we get near the medium size screen from the big size screen, your navigation links and the text inside of the "Debate" section break some words, kindly fix it:

![Yours](https://user-images.githubusercontent.com/59691171/98282106-75effd00-1f7c-11eb-8784-a8e3f76814f7.png)

- [ ] On small screens, the "Featured Stories" section should come right after "Top Story", just like the original. Currently, on your page, we can see "My Turn" after "Top Story".

- [x] Please check my comments in your code below.

## Summary
- You rock, your page is nearing perfection, your attention to details is very good 👍 
- Your repository is very professional, keep up the good work 💪 
- We only need to fix these details before moving on 🚀 

Kindly make the requested changes and submit for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-05 18:39 UTC, MuriloRoque commented on README.md
> +### Deployment
- [ ] Remove these sections from your README if you are not using them.

2020-11-05 18:39 UTC, MuriloRoque commented on index.html
> +  <link href="boo" -->
- [ ] Please remove commented pieces of code.

2020-11-05 18:39 UTC, MuriloRoque commented on index.html
> +  <!-- Bootstrap CSS -->
- [ ] You need to install Bootstrap in your project with any means mentioned in their webpage [here](https://getbootstrap.com/docs/4.5/getting-started/introduction/). Downloading the whole CSS file increases the size of your project and could impact any future changes you want to make to it. I couldn't find this suggestion on the Bootstrap page, if you have any sources instructing you to do what you did, can you please send it to me?

2020-11-05 18:39 UTC, MuriloRoque commented on test.html
> +<!DOCTYPE html>
- [ ] If you are not using this file, please delete it.

2020-11-06 16:17 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello again @kunmi02 and @bashforger :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-06 16:23 UTC, bashforger commented
Thank you very much, @MuriloRoque

2020-11-06 16:23 UTC, merged